### ISSUE TITLE
Error - Problem handling command KeyError

### ISSUE THREAD

**Issue by gordonych** [automaton82/MQTT-concord4#5]
Hi there. First of all, thanks for creating this and keep up the good work. I've just found this on GITHUB and decide to try it. However, while zone 1 to 10 is working, zone 11 to 17 is giving me error upon start up. Any idea what the problem is?

2020-12-18 22:43:54,836 [concord.py:handle_message()] - ERROR - Problem handling command KeyError(11,)
'090301000D000B000025'
2020-12-18 22:43:54,840 [concord.py:handle_message()] - ERROR - Traceback (most recent call last):
  File "/home/gyoung/Downloads/MQTT-concord4-master/concord/concord.py", line 487, in handle_message
    handler(decoded_command)
  File "concordsvr_mqtt.py", line 586, in panelMessageHandler
    zone_info['zone_text'] = FRIENDLY_ZONE_NAME_MAP[zk]
KeyError: 11

2020-12-18 22:43:55,345 [concord.py:handle_message()] - ERROR - Problem handling command KeyError(12,)
'090301000D000C000026'
2020-12-18 22:43:55,347 [concord.py:handle_message()] - ERROR - Traceback (most recent call last):
  File "/home/gyoung/Downloads/MQTT-concord4-master/concord/concord.py", line 487, in handle_message
    handler(decoded_command)
  File "concordsvr_mqtt.py", line 586, in panelMessageHandler
    zone_info['zone_text'] = FRIENDLY_ZONE_NAME_MAP[zk]
KeyError: 12

2020-12-18 22:43:55,853 [concord.py:handle_message()] - ERROR - Problem handling command KeyError(13,)
'090301000D000D000027'
2020-12-18 22:43:55,855 [concord.py:handle_message()] - ERROR - Traceback (most recent call last):
  File "/home/gyoung/Downloads/MQTT-concord4-master/concord/concord.py", line 487, in handle_message
    handler(decoded_command)
  File "concordsvr_mqtt.py", line 586, in panelMessageHandler
    zone_info['zone_text'] = FRIENDLY_ZONE_NAME_MAP[zk]
KeyError: 13

2020-12-18 22:43:56,361 [concord.py:handle_message()] - ERROR - Problem handling command KeyError(14,)
'090301000D000E000028'
2020-12-18 22:43:56,363 [concord.py:handle_message()] - ERROR - Traceback (most recent call last):
  File "/home/gyoung/Downloads/MQTT-concord4-master/concord/concord.py", line 487, in handle_message
    handler(decoded_command)
  File "concordsvr_mqtt.py", line 586, in panelMessageHandler
    zone_info['zone_text'] = FRIENDLY_ZONE_NAME_MAP[zk]
KeyError: 14

2020-12-18 22:43:56,869 [concord.py:handle_message()] - ERROR - Problem handling command KeyError(15,)
'090301000A000F010027'
2020-12-18 22:43:56,871 [concord.py:handle_message()] - ERROR - Traceback (most recent call last):
  File "/home/gyoung/Downloads/MQTT-concord4-master/concord/concord.py", line 487, in handle_message
    handler(decoded_command)
  File "concordsvr_mqtt.py", line 586, in panelMessageHandler
    zone_info['zone_text'] = FRIENDLY_ZONE_NAME_MAP[zk]
KeyError: 15

2020-12-18 22:43:57,378 [concord.py:handle_message()] - ERROR - Problem handling command KeyError(16,)
'09030100010010020020'
2020-12-18 22:43:57,380 [concord.py:handle_message()] - ERROR - Traceback (most recent call last):
  File "/home/gyoung/Downloads/MQTT-concord4-master/concord/concord.py", line 487, in handle_message
    handler(decoded_command)
  File "concordsvr_mqtt.py", line 586, in panelMessageHandler
    zone_info['zone_text'] = FRIENDLY_ZONE_NAME_MAP[zk]
KeyError: 16

2020-12-18 22:43:57,886 [concord.py:handle_message()] - ERROR - Problem handling command KeyError(17,)
'09030100010011020021'
2020-12-18 22:43:57,888 [concord.py:handle_message()] - ERROR - Traceback (most recent call last):
  File "/home/gyoung/Downloads/MQTT-concord4-master/concord/concord.py", line 487, in handle_message
    handler(decoded_command)
  File "concordsvr_mqtt.py", line 586, in panelMessageHandler
    zone_info['zone_text'] = FRIENDLY_ZONE_NAME_MAP[zk]
KeyError: 17

**Comment by gordonych** [comment]
Issue is resolved after adding the zone to the FRIENDLY_ZONE_NAME_MAP  in concordsvr_mqtt.py
